version: '3'

services:
  db:
    image: 'postgres:13-alpine'
    environment:
      POSTGRES_USER: hyper
      POSTGRES_PASSWORD: kitten
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    depends_on:
      - 'db'
    build: .
    env_file:
      - '.env'
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
volumes:
  pgdata:
