version: '3'

services:
  db:
    image: 'postgres:13-alpine'
    environment:
      POSTGRES_USER: hyper
      POSTGRES_PASSWORD: kitten
    ports:
      - '5432:5432'

  web:
    depends_on:
      - 'db'
      # - 'cssbundler'
    build: .
    env_file:
      - '.env'
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'

  # cssbundler:
  #   build: .
  #   environment:
  #     - NODE_ENV=development
  #     - RAILS_ENV=development
  #   command: yarn build:css --watch
  #   volumes:
  #     - '.:/app'
